# Generated by Django 4.0.5 on 2022-06-21 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('thumbnail', models.FileField(upload_to='product/', verbose_name='썸네일')),
                ('description', models.TextField(null=True, verbose_name='본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='글 작성 시간')),
                ('post_start_day', models.DateField(null=True, verbose_name='노출 시작일')),
                ('post_end_day', models.DateField(null=True, verbose_name='노출 종료일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
